<h1 align=center style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazir" color="#0099cc">
درآمد
</font>
</h1>

<h2 align=right style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazir" color="#0099cc">
مقدمه و صورت مسئله
</font>
</h2>

<p dir=rtl style="direction: rtl; text-align: justify; line-height:200%; font-family:vazir; font-size:medium">
<font face="vazir" size=3>
    در این تمرین قصد داریم درخت تصمیمی بسازیم که قادر باشد با دریافت یک سری ویژگی‌های شخصی و شغلی از شهروندان آمریکایی پیش‌بینی کند آیا شخص درآمد سالانه‌ی بالای ۵۰ هزار دلار خواهد داشت یا خیر. مجموعه‌داده‌ی مورداستفاده و صورت مسئله بسیار خوش‌تعریف است، با این حال جهت پیش‌پردازش مناسب ویژگی‌ها و همچنین دست‌یابی به یک مدل  با عملکرد بالا نیاز است از تکنیک‌های مختلف مهندسی ویژگی و فوت‌و‌فن‌های مرتبط با درخت تصمیم که در درسنامه‌ها آموخته‌اید استفاده کنید. بهره‌گیری از این تکنیک‌ها جهت مواجهه با چالش‌های عملی می‌تواند به‌خوبی شما را برای استفاده از این مدل در دنیای واقعی آماده کند.‌
</font>
</p>

<h2 align=right style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazir" color="#0099cc">
وارد کردن کتابخانه‌های مورد نیاز
</font>
</h2>

<p dir=rtl style="direction: rtl; text-align: justify; line-height:200%; font-family:vazir; font-size:medium">
<font face="vazir" size=3>
    ابتدا کتابخانه‌های مورد نیازتان را وارد کنید.
</font>
</p>

In [1]:
import numpy as np
import pandas as pd

<h2 align=right style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazir" color="#0099cc">
معرفی مجموعه داده
</font>
</h2>

<p dir=rtl style="direction: rtl; text-align: justify; line-height:200%; font-family:vazir; font-size:medium">
<font face="vazir" size=3>
    هر نمونه از این مجموعه‌داده با ویژگی‌هایی که در جدول زیر شرح داده شده همراه است. ستون <code>income</code> متغیر هدف مسئله است که درآمد شخص را نشان می‌دهد. 
</font>
</p>
<center>
<div dir=rtl style="direction: rtl;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazir" size=3>
    
|ستون|توضیحات|
|:------:|:---:|
|age|سن|
|workclass|یک عبارت کلی که نشان‌دهنده‌ی وضعیت شغلی فرد است.|
|fnlwgt|وزن نهایی، به عبارت دیگر تعداد افرادی که سرشماری باور دارد این ردیف بازنمایی می‌کند (نماینده‌ی آنهاست). |
|education|بیشترین سطح تحصیلات فرد |
|education.num|بیشترین سطح تحصیلات فرد به شکل عددی |
|marital.status|وضعیت تاهل فرد. توجه شود که <code>Married-­civ-­spouse</code> به معنی همسر غیرنظامی و <code>Married-­AF-­spouse</code> به معنی همسر نظامی است.|
|occupation|نوع کلی شغل یک فرد |
|relationship|رابطه‌ی این فرد با دیگران، به عنوان مثال همسر (<code>Husband</code>). هر داده تنها دارای یک رابطه است. |
|race|نژاد |
|sex| جنسیت بیولوژیکی فرد |
|capital.gain|سود سرمایه‌ی فرد  |
|capital.loss| زیان سرمایه‌ی فرد |
|hours.per.week| ساعت‌هایی که فرد گزارش داده در یک هفته کار می‌کند. |
|native.country| سرزمین مادری |
|income|درآمد، کمتر یا مساوی ۵۰ هزار دلار (<code dir=ltr><=50K</code>) یا بیشتر از آن (<code dir=ltr>>50K</code>) |

</font>
</div>
</center>

<h2 align=right style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazir" color="#0099cc">
خواندن مجموعه داده
</font>
</h2>

<p dir=rtl style="direction: rtl; text-align: justify; line-height:200%; font-family:vazir; font-size:medium">
<font face="vazir" size=3>
    در ابتدا نیاز است فایل‌های مجموعه‌داده را بخوانید. نمونه‌های آموزشی در فایل <code>train.csv</code> و نمونه‌های آزمون که باید دسته‌ی آن‌ها را پیش‌بینی کنید در فایل <code>test.csv</code> ذخیره شده‌اند. اگر لازم دانستید می‌توانید به دلخواه خود بخشی از مجموعه‌ی آموزشی را به عنوان مجموعه‌ی اعتبارسنجی نیز جدا کنید.
</font>
</p>

In [2]:
train_data = pd.read_csv('../data/train.csv')
train_data

,age,workclass,fnlwgt,education,education.num,marital.status,occupation,relationship,race,sex,capital.gain,capital.loss,hours.per.week,native.country,income
0,40,Self-emp-not-inc,223881,Prof-school,15,Married-civ-spouse,Prof-specialty,Husband,White,Male,99999,0,70,United-States,>50K
1,30,Private,149118,HS-grad,9,Divorced,Craft-repair,Not-in-family,White,Female,0,0,40,United-States,<=50K
2,46,Private,109209,Some-college,10,Married-civ-spouse,Adm-clerical,Husband,White,Male,0,0,40,United-States,>50K
3,32,Private,229566,Assoc-voc,11,Married-civ-spouse,Other-service,Husband,White,Male,0,0,60,United-States,>50K
4,54,?,148657,Preschool,1,Married-civ-spouse,?,Wife,White,Female,0,0,40,Mexico,<=50K
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
24995,40,Private,130834,Some-college,10,Never-married,Adm-clerical,Not-in-family,White,Female,0,0,40,United-States,<=50K
24996,31,Local-gov,33124,Bachelors,13,Never-married,Prof-specialty,Not-in-family,White,Female,0,0,50,United-States,<=50K
24997,38,Federal-gov,190895,Bachelors,13,Married-civ-spouse,Prof-specialty,Husband,White,Male,0,0,40,?,>50K
24998,23,Private,420973,Bachelors,13,Never-married,Prof-specialty,Not-in-family,White,Female,0,0,40,United-States,<=50K
24999,60,Private,88055,10th,6,Married-civ-spouse,Transport-moving,Husband,White,Male,0,0,40,United-States,<=50K

In [3]:
test_data = pd.read_csv('../data/test.csv')
test_data

,age,workclass,fnlwgt,education,education.num,marital.status,occupation,relationship,race,sex,capital.gain,capital.loss,hours.per.week,native.country
0,31,Private,176711,HS-grad,9,Married-civ-spouse,Transport-moving,Husband,White,Male,0,0,38,United-States
1,40,Private,120277,Some-college,10,Never-married,Sales,Not-in-family,White,Male,0,0,40,United-States
2,43,Private,299197,Some-college,10,Married-civ-spouse,Adm-clerical,Husband,White,Male,0,0,40,United-States
3,70,Self-emp-inc,188260,HS-grad,9,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,16,United-States
4,51,Private,254211,Bachelors,13,Married-civ-spouse,Craft-repair,Husband,White,Male,0,0,20,United-States
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7159,37,Self-emp-not-inc,75050,Assoc-voc,11,Married-civ-spouse,Craft-repair,Husband,White,Male,0,0,55,United-States
7160,36,Private,156780,HS-grad,9,Never-married,Sales,Other-relative,Asian-Pac-Islander,Female,0,0,40,?
7161,34,Private,381153,HS-grad,9,Married-civ-spouse,Transport-moving,Husband,White,Male,0,0,40,United-States
7162,59,Private,294395,Masters,14,Widowed,Prof-specialty,Not-in-family,White,Female,0,0,40,United-States
7163,24,State-gov,506329,Some-college,10,Never-married,Adm-clerical,Own-child,Asian-Pac-Islander,Male,0,0,40,?

<h2 align=right style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazir" color="#0099cc">
پیش‌پردازش و مهندسی ویژگی
</font>
</h2>

<p dir=rtl style="direction: rtl; text-align: justify; line-height:200%; font-family:vazir; font-size:medium">
<font face="vazir" size=3>
    در این سوال شما می‌توانید از هر تکنیک پیش‌پردازش/مهندسی ویژگی که در فصل‌های گذشته آموختید، استفاده کنید. توجه داشته باشید که انتخاب شما در بخش بعدی یعنی مدل‌سازی می‌تواند مراحلی که در این بخش طی می‌کنید را تحت تاثیر قرار دهد. بنابراین پیشنهاد می‌کنیم مواردی همچون مدیریت مقادیر گم‌شده، ویژگی‌های دسته‌ای و غیره را پس از مطالعه‌ی بخش بعد انجام دهید.
    <br>
    تکنیک‌هایی که در این بخش استفاده می‌کنید به شکل مستقیم مورد ارزیابی توسط سامانه داوری قرار <b>نمی‌گیرند.</b> بلکه همه آن‌ها در دقت مدل شما تاثیر خواهند گذاشت؛ بنابراین هر چه پیش‌پردازش/مهندسی ویژگی بهتری انجام دهید تا دقت مدل بهبود پیدا کند، امتیاز بیشتری از این سوال کسب خواهید کرد.
</font>
</p>

<p dir=rtl style="direction: rtl; text-align: justify; line-height:200%; font-family:vazir; font-size:medium">
<font face="vazir" size=3>
    <i>
    پیش از هر چیز مجموعه‌داده را از نظر توازن بررسی کنیم. طبق کد پایین متوجه خواهیم شد که این مجموعه‌داده به‌شدت نامتوازن است و باید از تکنیک‌های مختلفی که در درسنامه‌ی مجموعه‌داده‌ی نامتوازن آموخته‌ایم استفاده کنیم تا به مدلی با عملکرد پایدارتر و بهتر دست یابیم. ما فعلاً تغییری در مجموعه‌داده نخواهیم داد و توازن را در هنگام مدل‌سازی رعایت خواهیم کرد.
    </i>
</font>
</p>

In [4]:
train_data['income'].value_counts()

<=50K    18955
>50K      6045
Name: income, dtype: int64

<p dir=rtl style="direction: rtl; text-align: justify; line-height:200%; font-family:vazir; font-size:medium">
<font face="vazir" size=3>
    <i>
    حال به‌صورت کلی نگاهی به ویژگی‌ها بی‌اندازیم و نوع آن‌ها و تعداد مقادیر یکتای آن‌ها را بررسی کنیم.
    </i>
</font>
</p>

In [5]:
train_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25000 entries, 0 to 24999
Data columns (total 15 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   age             25000 non-null  int64
 1   workclass       25000 non-null  object
 2   fnlwgt          25000 non-null  int64
 3   education       25000 non-null  object
 4   education.num   25000 non-null  int64
 5   marital.status  25000 non-null  object
 6   occupation      25000 non-null  object
 7   relationship    25000 non-null  object
 8   race            25000 non-null  object
 9   sex             25000 non-null  object
 10  capital.gain    25000 non-null  int64
 11  capital.loss    25000 non-null  int64
 12  hours.per.week  25000 non-null  int64
 13  native.country  25000 non-null  object
 14  income          25000 non-null  object
dtypes: int64(6), object(9)
memory usage: 2.9+ MB

In [6]:
train_data.nunique()

age                  73
workclass             9
fnlwgt            17876
education            16
education.num        16
marital.status        7
occupation           15
relationship          6
race                  5
sex                   2
capital.gain        117
capital.loss         90
hours.per.week       93
native.country       41
income                2
dtype: int64

<p dir=rtl style="direction: rtl; text-align: justify; line-height:200%; font-family:vazir; font-size:medium">
<font face="vazir" size=3>
    <i>
    اگر کمی دقت کرده باشید دو ویژگی <code>education</code> و <code>education.num</code> در واقع نشانگر یک ویژگی هستند. بنابراین می‌توانیم ستون <code>education</code> را که از نوع دسته‌ای هست حذف کرده و تنها ستون <code>education.num</code> را که به‌صورت عددی است نگه داریم.
    </i>
</font>
</p>

In [7]:
train_data = train_data.drop(columns=['education'])
test_data = test_data.drop(columns=['education'])

<p dir=rtl style="direction: rtl; text-align: justify; line-height:200%; font-family:vazir; font-size:medium">
<font face="vazir" size=3>
    <i>
    اما وقت آن رسیده که مقادیر گم‌شده‌ی این مجموعه‌داده را مورد بررسی قرار دهیم. برای این کار ابتدا به کمک کد زیر تعداد مقادیر گم‌شده‌ی هر ستون را بررسی می‌کنیم.
    </i>
</font>
</p>

In [8]:
train_data.isnull().sum()

age               0
workclass         0
fnlwgt            0
education.num     0
marital.status    0
occupation        0
relationship      0
race              0
sex               0
capital.gain      0
capital.loss      0
hours.per.week    0
native.country    0
income            0
dtype: int64

<p dir=rtl style="direction: rtl; text-align: justify; line-height:200%; font-family:vazir; font-size:medium">
<font face="vazir" size=3>
    <i>
    شاید با توجه به نتایج بالا فکر کنید پس این مجموعه‌داده شامل مقادیر گم‌شده نیست اما اگر کمی مجموعه‌داده را بررسی کنید متوجه خواهید شد که برخی مقادیر با علامت <code>?</code> ذخیره شده‌اند. بنابراین مقادیر گم‌شده در این مجموعه‌داده با علامت سوال نشان داده شده و بهتر است که این مقادیر را به <code>NaN</code> تبدیل کنیم تا بتوانیم مقادیر گم‌شده را به شکلی متعارف مدیریت کنیم. 
    </i>
</font>
</p>

In [9]:
train_data[4:5]

,age,workclass,fnlwgt,education.num,marital.status,occupation,relationship,race,sex,capital.gain,capital.loss,hours.per.week,native.country,income
4,54,?,148657,1,Married-civ-spouse,?,Wife,White,Female,0,0,40,Mexico,<=50K

In [10]:
train_data = train_data.replace('?', np.NaN)
test_data = test_data.replace('?', np.NaN)

<p dir=rtl style="direction: rtl; text-align: justify; line-height:200%; font-family:vazir; font-size:medium">
<font face="vazir" size=3>
    <i>
    اکنون بررسی کنیم چه تعداد مقادیر کدام ستون‌ها گم‌شده‌اند تا بتوانیم آن‌ها را مدیریت کنیم. توجه داشته باشید که در مجموعه‌داده‌‌ی آزمون هم برخی مقادیر گم‌شده وجود دارد.
    </i>
</font>
</p>

In [11]:
train_data.isnull().sum()

age                  0
workclass         1429
fnlwgt               0
education.num        0
marital.status       0
occupation        1434
relationship         0
race                 0
sex                  0
capital.gain         0
capital.loss         0
hours.per.week       0
native.country     437
income               0
dtype: int64

In [12]:
test_data.isnull().sum()

age                 0
workclass         387
fnlwgt              0
education.num       0
marital.status      0
occupation        389
relationship        0
race                0
sex                 0
capital.gain        0
capital.loss        0
hours.per.week      0
native.country    138
dtype: int64

<p dir=rtl style="direction: rtl; text-align: justify; line-height:200%; font-family:vazir; font-size:medium">
<font face="vazir" size=3>
    <i>
   اگر از کتابخانه‌ی <code>H2O</code> استفاده کنیم نیازی نیست تا خودمان به‌صورت دستی مقادیر گم‌شده را مدیریت کنیم و درخت تصمیم این کتابخانه مستقیماً از این نوع مقادیر پشتیبانی می‌کند.
    <br>
    اما اگر از <code>scikit-learn</code> استفاده کنیم جهت مدیریت مقادیر گم‌شده توجه به اینکه ویژگی‌هایی که شامل مقادیر گم‌شده هستند از نوع دسته‌ای هستند یکی از ساده‌ترین روش‌ها این است که آن‌ها را با پرتکرارترین مقدار (دسته) پُر کنیم. در کد زیر ابتدا پرتکرارترین دسته‌ی ویژگی را پیدا کرده سپس تمام مقادیر <code>NaN</code> آن ویژگی را هم در مجموعه‌ی آموزشی و هم آزمون را با این دسته جایگزین می‌کنیم. توجه شود که برای پیدا کردن پرتکرارترین دسته تنها از مجموعه‌ی آموزشی استفاده کرده‌ایم و آن را به مجموعه‌ی آزمون تعمیم داده‌ایم. از آن جهت که در این راه‌حل هر دو کتابخانه را امتحان خواهیم کرد، تغییرات مربوط به <code>scikit-learn</code> را در دو دیتافریم کپی‌شده اعمال می‌کنیم.
    </i>
</font>
</p>

In [13]:
sk_train = train_data.copy()
sk_test = test_data.copy()

In [14]:
cols = ['workclass', 'occupation', 'native.country']

for col in cols:
    most_frequent = sk_train[col].value_counts().sort_values(ascending=False).index[0]
    sk_train[col].fillna(most_frequent, inplace=True)
    sk_test[col].fillna(most_frequent, inplace=True)
    print('All the missing values in column', col, 'are replaced with', most_frequent)

All the missing values in column workclass are replaced with Private
All the missing values in column occupation are replaced with Prof-specialty
All the missing values in column native.country are replaced with United-States

<p dir=rtl style="direction: rtl; text-align: justify; line-height:200%; font-family:vazir; font-size:medium">
<font face="vazir" size=3>
    <i>
    حال به سراغ مدیریت ویژگی‌های دسته‌ای می‌رویم.
    باز هم اگر از کتابخانه‌ی <code>H2O</code> استفاده کنیم نیازی به مدیریت دستی ویژگی‌های دسته‌ای نداریم و این کتابخانه مستقیماً از ویژگی‌های دسته‌ای پشتیبانی می‌کند.
اما از آنجا که کتابخانه‌ی <code>scikit-learn</code> از مقادیر دسته‌ای پشتیبانی نمی‌کند نیاز است تا آن‌ها را به کمک روش‌هایی که در فصل مهندسی ویژگی آموختیم به مقادیر عددی تبدیل کنیم. در ابتدا ستون <code>income</code> را که همان متغیر هدف است به کمک <code>LabelEncoder</code> به برچسب‌های عددی تبدیل می‌کنیم.
    </i>
</font>
</p>

In [15]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
sk_train['income'] = le.fit_transform(sk_train['income'])
to_label = dict(zip(le.classes_, le.transform(le.classes_)))
to_class = dict(zip(le.transform(le.classes_), le.classes_))
print(to_label)

{'<=50K': 0, '>50K': 1}

<p dir=rtl style="direction: rtl; text-align: justify; line-height:200%; font-family:vazir; font-size:medium">
<font face="vazir" size=3>
    <i>
    حال باید درباره سایر ویژگی‌های دسته‌ای تصمیم بگیریم. ساده‌ترین راه این است که به هر دسته یک عدد اختصاص دهیم و دسته‌ها را با این اعداد جایگزین کنیم. هرچند که این روش معایب خود را دارد اما به دلیل آن‌که قصد نداریم از روشی مانند One-Hot استفاده کرده و تعداد ویژگی‌ها را به شدت افزایش دهیم، به کمک تابع <code>OrdinalEncoder</code> از همین تکنیک استفاده خواهیم کرد. توجه داشته باشید که در نمونه‌های آزمون ممکن است دسته‌ای وجود داشته باشد که در هنگام آموزش آن را ندیده باشید. بنابراین می‌توانیم آرگومان <code>handle_unknown</code> را برابر <code>'use_encoded_value'</code> قرار دهید تا به جای این دسته‌ها مقداری که برای <code>unknown_value</code> تنظیم می‌کنید در نظر گرفته شود. برای این آرگومان می‌توانیم مقدار <code dir=ltr>-1</code> را در نظر بگیریم.
    </i>
</font>
</p>

In [16]:
from sklearn.preprocessing import OrdinalEncoder

categorical_cols = sk_train.select_dtypes(include = "object").columns

enc = OrdinalEncoder(handle_unknown='use_encoded_value', unknown_value=-1)

sk_train[categorical_cols] = enc.fit_transform(sk_train[categorical_cols])
sk_test[categorical_cols] = enc.transform(sk_test[categorical_cols])

<p dir=rtl style="direction: rtl; text-align: justify; line-height:200%; font-family:vazir; font-size:medium">
<font face="vazir" size=3>
    <i>
    یکبار دیگر ستون‌های مجموعه‌های خود را بررسی می‌کنیم تا از تبدیل نوع آن‌ها مطمئن شویم.
    </i>
</font>
</p>

In [17]:
sk_train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25000 entries, 0 to 24999
Data columns (total 14 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   age             25000 non-null  int64
 1   workclass       25000 non-null  float64
 2   fnlwgt          25000 non-null  int64
 3   education.num   25000 non-null  int64
 4   marital.status  25000 non-null  float64
 5   occupation      25000 non-null  float64
 6   relationship    25000 non-null  float64
 7   race            25000 non-null  float64
 8   sex             25000 non-null  float64
 9   capital.gain    25000 non-null  int64
 10  capital.loss    25000 non-null  int64
 11  hours.per.week  25000 non-null  int64
 12  native.country  25000 non-null  float64
 13  income          25000 non-null  int32
dtypes: float64(7), int32(1), int64(6)
memory usage: 2.6 MB

In [18]:
sk_test.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7164 entries, 0 to 7163
Data columns (total 13 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   age             7164 non-null   int64
 1   workclass       7164 non-null   float64
 2   fnlwgt          7164 non-null   int64
 3   education.num   7164 non-null   int64
 4   marital.status  7164 non-null   float64
 5   occupation      7164 non-null   float64
 6   relationship    7164 non-null   float64
 7   race            7164 non-null   float64
 8   sex             7164 non-null   float64
 9   capital.gain    7164 non-null   int64
 10  capital.loss    7164 non-null   int64
 11  hours.per.week  7164 non-null   int64
 12  native.country  7164 non-null   float64
dtypes: float64(7), int64(6)
memory usage: 727.7 KB

<p dir=rtl style="direction: rtl; text-align: justify; line-height:200%; font-family:vazir; font-size:medium">
<font face="vazir" size=3>
    <i>
    حال ستون متغیر هدف را از ویژگی‌ها جدا می‌کنیم تا بتوانیم به عنوان ورودی به مدل خود بدهیم.
    </i>
</font>
</p>

In [19]:
sk_label = sk_train['income']
sk_train = sk_train.drop(columns=['income'])

<h2 align=right style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazir" color="#0099cc">
مدل‌سازی
</font>
</h2>

<p dir=rtl style="direction: rtl; text-align: justify; line-height:200%; font-family:vazir; font-size:medium">
<font face="vazir" size=3>
    حال که داده را پاکسازی کرده و احتمالا ویژگی‌هایی را به آن افزوده یا از آن حذف کرده‌اید، وقت آن است که مدلی آموزش دهید که بتواند متغیر هدف این مسئله را پیش‌بینی کند. در این تمرین انتخاب کتابخانه‌ای که درخت تصمیم را در اختیارتان بگذارد به عهده‌ی خود شماست. می‌توانید همچون همیشه از کتابخانه‌ی <code>scikit-learn</code> استفاده کنید اما توجه داشته باشید که درخت تصمیم این کتابخانه از قابلیت‌های مهمی مثل مدیریت مستقیم مقادیر گم‌شده و ویژگی‌های دسته‌ای پشتیبانی نمی‌کند و نیاز خواهید داشت که مراحل پیش‌پردازش مختلفی را انجام دهید. اما پیشنهاد بهتر این است که با توجه به توضیحاتی که در ادامه خواهیم داد از کتابخانه‌ی <code>H2O</code> استفاده کنید که از قابلیت‌های ذکرشده پشتیبانی می‌کند و نیازی به طی کردن مراحل اضافی نیست (البته معمولاً عملکرد درخت تصمیم این کتابخانه هم بهتر از درخت تصمیم <code>scikit-learn</code> است). با این حال ما مقدار آستانه‌ی پاس شدن این تمرین را به‌گونه‌ای تنظیم کرده‌ایم که متعادل باشد و با هر دو روش بتوانید امتیاز موردنظر را کسب کنید. حتی می‌توانید خفن‌تر (😎) عمل کرده و با هرکدام از کتابخانه‌ها درخت تصمیمی بسازید و عملکرد آن‌ها را مقایسه کنید. 
</font>
</p>

<h3 align=right style="direction: rtl;text-align: right;line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazir" color="#0099cc">
    استفاده از <code>scikit-learn</code>
</font>
</h3>


<p dir=rtl style="direction: rtl; text-align: justify; line-height:200%; font-family:vazir; font-size:medium">
<font face="vazir" size=3>
    به منظور استفاده از درخت تصمیم برای مسائل دسته‌بندی می‌توانید از <code>DecisionTreeClassifier</code> موجود در کتابخانه‌ی <code>scikit-learn</code> استفاده کنید. نحوه‌ی آموزش مدل و پیش‌بینی برای نمونه‌های جدید همچون تمام مدل‌های این کتابخانه است، اما برخی پارامترها و آرگومان‌های بسیار کاربردی این کلاس در جدول زیر شرح داده شده‌اند. جهت بررسی پارامترها و توضیحات بیشتر می‌توانید از <a href="https://scikit-learn.org/stable/modules/generated/sklearn.tree.DecisionTreeClassifier.html#sklearn.tree.DecisionTreeClassifier" target="__blank">این لینک</a>، سند اصلی آن را مطالعه کنید.
</font>
</p>

<center>
<p dir=ltr style="direction: ltr; line-height:200%; font-family:vazir; font-size:medium">
<font face="vazir" size=3>
    <code dir=ltr>from sklearn.tree import DecisionTreeClassifier</code>
    <br>
    <code dir=ltr>clf = DecisionTreeClassifier()</code>
</font>
</p>
</center>

<center>
<div dir=rtl style="direction: rtl;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazir" size=3>
    
|پارامتر|توضیحات|مقادیر ممکن|مقدار پیش‌فرض|
|:------:|:---:|:---:|:---:|
|<code>criterion</code>|معیار ارزیابی تفکیک (معیار ناخالصی یا بهره اطلاعاتی)|<code>"gini"</code>، <code>"entropy"</code> یا <code>"log_loss"</code>|<code>"gini"</code>|
|<code>max_depth</code>|حداکثر عمق درخت|عدد <code>int</code>|<code>None</code>|
|<code>min_samples_split</code>|حداقل نمونه‌ها جهت تفکیک یک گره‌ی داخلی|عدد <code>int</code> (تعداد) یا <code>float</code> (درصد)|<code>2</code>|
|<code>min_samples_leaf</code>|حداقل نمونه‌های یک برگ. یک گره تنها در صورتی تفکیک می‌یابد که هرکدام از شاخه‌های راست و چپ آن حداقل شامل این تعداد نمونه باشد|عدد <code>int</code> (تعداد) یا <code>float</code> (درصد)|<code>1</code>|
|<code>max_features</code>|تعداد ویژگی‌هایی که در هنگام جستجوی بهترین تفکیک بررسی می‌شوند|عدد <code>int</code> (تعداد)، <code>float</code> (درصد)، ، <code>"sqrt"</code> (جذر)، <code>"log2"</code> (لگاریتم در مبنای ۲) یا <code>None</code> (تمام ویژگی‌ها)|<code>None</code>|
|<code>min_impurity_decrease</code>|یک گره هنگامی تفکیک می‌شود که آن تفکیک باعث کاهش ناخالصی بیشتر یا مساوی این مقدار شود|عدد <code>float</code>|<code>0.0</code>|
    
</font>
</div>
</center>


<p dir=rtl style="direction: rtl; text-align: justify; line-height:200%; font-family:vazir; font-size:medium">
<font face="vazir" size=3>
    <b>نکته:</b>
    پارامتر کاربردی دیگری به نام <code>ccp_alpha</code> وجود دارد که به منظور پس‌هرس درخت تصمیم با روش Minimal Cost-Complexity استفاده می‌شود. از آنجا که شرح این تکنیک خارج از بحث این فصل است، ضرورتی بر استفاده از آن تعریف نشده است. اما در صورت علاقه می‌توانید برای مطالعه‌ی این روش جذاب به بخش <a href="https://scikit-learn.org/stable/modules/tree.html#minimal-cost-complexity-pruning" target="__blank">معرفی آن</a> در <code>scikit-learn</code> یا فصل سوم کتاب <i>Classification and Regression Trees</i> نوشته‌ی <i>Leo Breiman</i> مراجعه کرده و یا به شکلی ساده‌تر و جذاب‌تر <a href="https://youtu.be/D0efHEJsfHo" target="__blank">این ویدیو</a> را از <i>StatQuest</i> مشاهده کنید.  
</font>
</p>

<p dir=rtl style="direction: rtl; text-align: justify; line-height:200%; font-family:vazir; font-size:medium">
<font face="vazir" size=3>
    اگر مدل را <code>clf</code> بنامیم، پس از آموزش آن می‌توانید به کمک توابع یا متغیرهای زیر، برخی ویژگی‌های مهم درخت تصمیم را مورد بررسی قرار دهید.
</font>
</p>

<center>
<div dir=rtl style="direction: rtl;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazir" size=3>
    
|پارامتر|توضیحات|
|:------:|:---:|
| <code dir=ltr>clf.get_depth()</code> | عمق درخت |
| <code dir=ltr>clf.get_n_leaves()</code> | تعداد برگ‌های درخت |
| <code dir=ltr>clf.feature_names_in_</code> | ویژگی‌های ورودی |
| <code dir=ltr>clf.feature_importances_</code> | اهمیت هر ویژگی طبق معیار ناخالصی |
    
</font>
</div>
</center>

<p dir=rtl style="direction: rtl; text-align: justify; line-height:200%; font-family:vazir; font-size:medium">
<font face="vazir" size=3>
    همچنین طبق کد زیر می‌توانید به کمک تابع <code>plot_tree</code> درخت تصمیم خود را ترسیم کنید. البته در صورتی‌که درخت حاصل بزرگ باشد ترسیم آن چندان جالب به نظر نخواهد رسید.
</font>
</p>

<center>
<p dir=ltr style="direction: ltr; line-height:200%; font-family:vazir; font-size:medium">
<font face="vazir" size=3>
    <code dir=ltr>from sklearn import tree</code>
    <br>
    <code dir=ltr>tree.plot_tree(clf)</code>
</font>
</p>
</center>

<h3 align=right style="direction: rtl;text-align: right;line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazir" color="#0099cc">
    استفاده از <code>H2O</code>
</font>
</h3>


<p dir=rtl style="direction: rtl; text-align: justify; line-height:200%; font-family:vazir; font-size:medium">
<font face="vazir" size=3>
    در کتابخانه‌ی <code>H2O</code> درخت تصمیم به‌صورت مشخص پیاده‌سازی نشده اما به کمک ترفندی که شرح خواهیم داد می‌توانید به یک درخت تصمیم دست یابید. در این کتابخانه مدل‌های حرفه‌ای‌تری پیاده‌سازی شده که در واقع اساس آن‌ها درخت تصمیم است. یکی از این مدل‌ها «<i>جنگل تصادفی</i>» نام دارد که در این کتابخانه با نام <code>H2ORandomForestEstimator</code> در دسترس است و در فصل یادگیری تجمعی کاملاً با ساختار آن آشنا خواهید شد. این مدل در واقع متشکل از تعداد زیادی درخت تصمیم است. بنابراین اگر ما یک جنگل تصادفی بسازیم که تنها شامل یک درخت باشد  در واقع مدل همانند یک درخت تصمیم عمل خواهد کرد. البته نیاز است به شکل زیر برخی از پارامترهای آن را به گونه‌ای مقداردهی کنیم که رفتاری شبیه به درخت تصمیم داشته باشد.
</font>
</p>

<center>
<p dir=ltr style="direction: ltr; line-height:200%; font-family:vazir; font-size:medium">
<font face="vazir" size=3>
<code>from h2o.estimators import H2ORandomForestEstimator</code>
<br>
<code>model = H2ORandomForestEstimator(ntrees=1, sample_rate=1)</code>
</font>
</p>
</center>

<p dir=rtl style="direction: rtl; text-align: justify; line-height:200%; font-family:vazir; font-size:medium">
<font face="vazir" size=3>
    برخی از پارامترهای کاربردی این کلاس نیز در جدول زیر معرفی و شرح داده شده است. جهت بررسی پارامترها و توضیحات بیشتر می‌توانید از <a href="https://docs.h2o.ai/h2o/latest-stable/h2o-docs/data-science/drf.html" target="__blank">این لینک</a>، سند اصلی آن را مطالعه کنید.
</font>
</p>


<center>
<div dir=rtl style="direction: rtl;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazir" size=3>
    
|پارامتر|توضیحات|مقادیر ممکن|مقدار پیش‌فرض|
|:------:|:-----:|:---:|:---:|
|<code>mtries</code>|تعداد ویژگی‌هایی که به‌صورت تصادفی در هر سطح برای جستجوی بهترین تفکیک استفاده می‌شود| <code dir=ltr>-1</code> برای جذر، <code dir=ltr>-2</code> برای تمام ویژگی‌ها یا عدد بزرگتر یا مساوی <code>1</code> |<code dir=ltr>-1</code>|
|<code>max_depth</code>|حداکثر عمق درخت|عدد <code>int</code>|<code>20</code>|
|<code>min_rows</code>|حداقل نمونه‌های یک برگ. یک گره تنها در صورتی تفکیک می‌یابد که هرکدام از شاخه‌های راست و چپ آن حداقل شامل این تعداد نمونه باشد|عدد <code>int</code>|<code>1</code>|
|<code>min_split_improvement</code>|یک گره هنگامی تفکیک می‌شود که کاهش مربعات خطا حداقل به این میزان بهبود یابد|عدد کوچک (پیشنهاد می‌شود در بازه‌ی <code>1e-10</code> تا <code>1e-3</code> باشد)|<code>1e-05</code>|
|<code>categorical_encoding</code>|رویکرد مدیریت ویژگی‌های دسته‌ای|<code>"auto"</code> (به‌صورت پیش‌فرض معادل <code>"enum"</code>)، <code>"enum"</code> (پشتیبانی مستقیم از ویژگی دسته‌ای)، <code>"one_hot_explicit"</code> (کدگذاری one-hot)،  <code>"binary"</code> (کدگذاری باینری)، <code>"label_encoder"</code> (برچسب‌گذاری) و غیره|<code>"auto"</code>|
|<code>balance_classes</code>|متوازن‌سازی مجموعه‌داده به کمک نمونه‌افزایی کلاس اقلیت|<code>True</code> یا <code>False</code>|<code>False</code>|
|<code>nfolds</code>|تعداد قطعه‌ها در اعتبارسنجی متقاطع (cross-validation)|عدد <code>int</code>|<code>0</code>|
    
</font>
</div>
</center>

<p dir=rtl style="direction: rtl; text-align: justify; line-height:200%; font-family:vazir; font-size:medium">
<font face="vazir" size=3>
    برای استفاده از <code>H2O</code> پیش از هرچیز نیاز است مراحل راه‌اندازی آن را که در درسنامه‌ی مربوط به این کتابخانه شرح داده شد اجرا کرده باشید و همچنین دیتافریم‌های خود را به <code>H2OFrame</code> تبدیل کرده باشید. پس از آن می‌توانید به کمک مدل معرفی‌شده در بالا پارامترهای موردنظر خود را مقداردهی کنید. سپس جهت آموزش مدل نیاز است تابع <code dir=ltr>fit()</code> را با سه آرگومان مهم زیر صدا بزنید.
</font>
</p>

<center>
<div dir=rtl style="direction: rtl;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazir" size=3>
    
|پارامتر|توضیحات|
|:------:|:-----:|
|<code>x</code>| لیستی شامل نام ستون‌های ورودی (ویژگی‌ها) |
|<code>y</code>| نام ستون متغیر هدف |
|<code>training_frame</code>| داده‌های آموزشی از جنس <code>H2OFrame</code> |
|<code>validation_frame</code>| داده‌های اعتبارسنجی از جنس <code>H2OFrame</code> (دلخواه)|

    
</font>
</div>
</center>

<p dir=rtl style="direction: rtl; text-align: justify; line-height:200%; font-family:vazir; font-size:medium">
<font face="vazir" size=3>
    جهت پیش‌بینی نیز می‌توانید <code>H2OFrame</code> موردنظر خود را به تابع <code dir=ltr>predict()</code> بدهید تا مدل شروع به پیش‌بینی متغیر هدف برای نمونه‌های موردنظر شما کند. توجه داشته باشید که اگر قصد دارید مقادیر پیش‌بینی‌شده را به یک دیتافریم <code>pandas</code> تبدیل کنید می‌توانید از تابع <code dir=ltr>as_data_frame()</code> استفاده کنید. مقادیر پیش‌بینی‌شده در ستونی به نام <code>predict</code> در دیتافریم به‌دست‌آمده ذخیره شده‌اند. 
</font>
</p>

<h3 align=right style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazir" color="#0099cc">
آموزش مدل
</font>
</h3>

<p dir=rtl style="direction: rtl; text-align: justify; line-height:200%; font-family:vazir; font-size:medium">
<font face="vazir" size=3>
    اکنون وقت آن رسیده که با توجه به کتابخانه‌ی انتخابی، مدل را آموزش دهید.
</font>
</p>

<p dir=rtl style="direction: rtl; text-align: justify; line-height:200%; font-family:vazir; font-size:medium">
<font face="vazir" size=3>
    <i>
    اگر قصد استفاده از کتابخانه‌ی <code>scikit-learn</code> را داشته باشیم می‌توانیم به شکل زیر یک مدل را تعریف کرده و آموزش دهیم. توجه داشته باشید که به کمک آرگومان <code>class_weight</code> وزن نمونه‌های اقلیت (برچسب <code dir=ltr>>50K</code>) را بیشتر از نمونه‌های اکثریت (<code dir=ltr><=50K</code>) در نظر گرفته‌ایم.
    </i>
</font>
</p>

In [20]:
from sklearn.tree import DecisionTreeClassifier
clf = DecisionTreeClassifier(max_depth=10, min_samples_split=50, min_samples_leaf=8, class_weight={0: 0.4, 1: 0.6})
clf.fit(sk_train, sk_label)

DecisionTreeClassifier(class_weight={0: 0.4, 1: 0.6}, max_depth=10,
                       min_samples_leaf=8, min_samples_split=50)

<p dir=rtl style="direction: rtl; text-align: justify; line-height:200%; font-family:vazir; font-size:medium">
<font face="vazir" size=3>
    <i>
    حال نگاهی به جزئیات درخت به‌دست‌آمده بی‌اندازیم.
    </i>
</font>
</p>

In [21]:
print('-- Details of the acheived Decision Tree --')
print('Depth:', clf.get_depth())
print('Number of leaves:', clf.get_n_leaves())
print('\n--Feature importances --')
for feature, importance in sorted(zip(clf.feature_names_in_, clf.feature_importances_), key=lambda x: x[1], reverse=True):
    print(feature, '\t' ,importance)

-- Details of the acheived Decision Tree --
Depth: 10
Number of leaves: 179

--Feature importances --
relationship 	 0.43944885070379497
education.num 	 0.19631172110863576
capital.gain 	 0.18977038686210587
age 	 0.05852834711767802
hours.per.week 	 0.04023360014305677
capital.loss 	 0.03762718044015594
workclass 	 0.010908859829025489
fnlwgt 	 0.010649717742004289
occupation 	 0.009686926761051878
sex 	 0.002163325104004916
race 	 0.0016995419209027195
marital.status 	 0.00159757028426186
native.country 	 0.0013739719833214062

<p dir=rtl style="direction: rtl; text-align: justify; line-height:200%; font-family:vazir; font-size:medium">
<font face="vazir" size=3>
    <i>
    اگر هم قصد داشته باشیم از کتابخانه‌ی <code>H2O</code> استفاده کنیم ابتدا هسته‌ی آن را راه‌اندازی کرده و دیتافریم‌های خود را به <code>H2OFrame</code> تبدیل می‌کنیم.
    </i>
</font>
</p>

In [23]:
import h2o
h2o.init()

Checking whether there is an H2O instance running at http://localhost:54321 . connected.

--------------------------  -----------------------------
H2O_cluster_uptime:         22 secs
H2O_cluster_timezone:       Asia/Tehran
H2O_data_parsing_timezone:  UTC
H2O_cluster_version:        3.36.1.4
H2O_cluster_version_age:    2 months and 10 days
H2O_cluster_name:           H2O_from_python_parsa_2yzlei
H2O_cluster_total_nodes:    1
H2O_cluster_free_memory:    1.955 Gb
H2O_cluster_total_cores:    4
H2O_cluster_allowed_cores:  4
H2O_cluster_status:         locked, healthy
H2O_connection_url:         http://localhost:54321
H2O_connection_proxy:       {"http": null, "https": null}
H2O_internal_security:      False
Python_version:             3.9.7 final
--------------------------  -----------------------------

In [24]:
hf_train = h2o.H2OFrame(train_data)
hf_test = h2o.H2OFrame(test_data)

Parse progress: |████████████████████████████████████████████████████████████████| (done) 100%
Parse progress: |████████████████████████████████████████████████████████████████| (done) 100%

<p dir=rtl style="direction: rtl; text-align: justify; line-height:200%; font-family:vazir; font-size:medium">
<font face="vazir" size=3>
    <i>
    سپس باید یک لیست از ویژگی‌ها بسازیم. برای این کار نام ستون‌های فریم‌ را گرفته و ستون هدف را از آن حذف می‌کنیم.
    </i>
</font>
</p>

In [25]:
TARGET = 'income'
features = list(hf_train.columns)
features.remove(TARGET)

<p dir=rtl style="direction: rtl; text-align: justify; line-height:200%; font-family:vazir; font-size:medium">
<font face="vazir" size=3>
    <i>
    اکنون می‌توانیم پارامترهای موردنظر را مقداردهی کرده و مدل را آموزش دهیم. در اینجا با مقداردهی <code>True</code> به آرگومان <code>balance_classes</code> می‌توانیم از روش نمونه‌افزایی به کمک تکرار نمونه‌های اقلیت استفاده کنیم. البته این کتابخانه آرگومان‌های دیگری را جهت مدیریت توازن داده‌ها در اختیار شما قرار می‌دهد اما جهت حفظ سادگی از استفاده‌ی آن‌ها پرهیز کرده‌ایم.
    </i>
</font>
</p>

In [26]:
from h2o.estimators import H2ORandomForestEstimator

model = H2ORandomForestEstimator(ntrees=1, sample_rate=1, mtries=-2, max_depth=10,
                                 min_rows=8, min_split_improvement=1e-4,
                                 balance_classes=True, nfolds=5)

model.train(x=features, y=TARGET, training_frame=hf_train)

drf Model Build progress: |██████████████████████████████████████████████████████| (done) 100%
Model Details
=============
H2ORandomForestEstimator :  Distributed Random Forest
Model Key:  DRF_model_python_1665689504369_1


Model Summary:

,,number_of_trees,number_of_internal_trees,model_size_in_bytes,min_depth,max_depth,mean_depth,min_leaves,max_leaves,mean_leaves
0,,1.0,1.0,3218.0,10.0,10.0,10.0,239.0,239.0,239.0

ModelMetricsBinomial: drf
** Reported on train data. **

MSE: NaN
RMSE: NaN
LogLoss: NaN
Mean Per-Class Error: NaN
AUC: NaN
AUCPR: NaN
Gini: NaN

ModelMetricsBinomial: drf
** Reported on cross-validation data. **

MSE: 0.10192730734355099
RMSE: 0.3192605634016688
LogLoss: 0.605294876085934
Mean Per-Class Error: 0.18637875740265952
AUC: 0.8934657395655856
AUCPR: 0.7713852821401798
Gini: 0.7869314791311712

Confusion Matrix (Act/Pred) for max f1 @ threshold = 0.3738727492248246:

            <=50K    >50K   Error               Rate
0  <=50K  16157.0  2798.0  0.1476   (2798.0/18955.0)
1   >50K   1361.0  4684.0  0.2251    (1361.0/6045.0)
2  Total  17518.0  7482.0  0.1664   (4159.0/25000.0)

Maximum Metrics: Maximum metrics at their respective thresholds

                         metric  threshold         value    idx
0                        max f1   0.373873      0.692541  120.0
1                        max f2   0.147904      0.779413  246.0
2                  max f0point5   0.641620      0.725621   48.0
3                  max accuracy   0.495193      0.854760   85.0
4                 max precision   0.938584      0.963804    4.0
5                    max recall   0.000000      1.000000  399.0
6               max specificity   1.000000      0.996887    0.0
7              max absolute_mcc   0.446389      0.590508   95.0
8    max min_per_class_accuracy   0.295799      0.819520  159.0
9   max mean_per_class_accuracy   0.247889      0.821047  184.0
10                      max tns   1.000000  18896.000000    0.0
11                      max fns   1.000000   4510.000000    0.0
12                      max fps   0.000000  18955.000000  399.0
13                      max tps   0.000000   6045.000000  399.0
14                      max tnr   1.000000      0.996887    0.0
15                      max fnr   1.000000      0.746071    0.0
16                      max fpr   0.000000      1.000000  399.0
17                      max tpr   0.000000      1.000000  399.0

Gains/Lift Table: Avg response rate: Û²Û´Ù«Û±Û¸ %, avg score: Û²Û´Ù«Û±Û° %

,group,cumulative_data_fraction,lower_threshold,lift,cumulative_lift,response_rate,score,cumulative_response_rate,cumulative_score,capture_rate,cumulative_capture_rate,gain,cumulative_gain,kolmogorov_smirnov
0,1,0.06376,1.000000,3.982573,3.982573,0.962986,1.000000,0.962986,1.000000,0.253929,0.253929,298.257319,298.257319,0.250816
1,2,0.10152,0.753147,3.097356,3.653320,0.748941,0.789386,0.883373,0.921663,0.116956,0.370885,209.735599,265.331983,0.355269
2,3,0.15316,0.641620,2.748557,3.348267,0.664601,0.695929,0.809611,0.845554,0.141935,0.512821,174.855701,234.826660,0.474361
3,4,0.21188,0.500016,2.124169,3.009023,0.513624,0.547524,0.727582,0.762958,0.124731,0.637552,112.416864,200.902254,0.561424
4,5,0.30088,0.369777,1.565041,2.581894,0.378427,0.397347,0.624302,0.654811,0.139289,0.776840,56.504122,158.189432,0.627750
5,6,0.40396,0.177279,1.014253,2.181873,0.245246,0.261374,0.527577,0.554416,0.104549,0.881390,1.425315,118.187340,0.629688
6,7,0.50364,0.068763,0.585828,1.865986,0.141653,0.126373,0.451195,0.469698,0.058395,0.939785,-41.417167,86.598552,0.575237
7,8,0.61328,0.011412,0.200672,1.568267,0.048522,0.032487,0.379207,0.391535,0.022002,0.961787,-79.932822,56.826670,0.459650
8,9,0.70412,0.005204,0.071022,1.375104,0.017173,0.007806,0.332500,0.342029,0.006452,0.968238,-92.897828,37.510398,0.348349
9,10,0.82760,0.000287,0.024115,1.173533,0.005831,0.001670,0.283760,0.291247,0.002978,0.971216,-97.588543,17.353296,0.189417
10,11,1.00000,0.000000,0.166961,1.000000,0.040371,0.000060,0.241800,0.241046,0.028784,1.000000,-83.303875,0.000000,0.000000

Cross-Validation Metrics Summary:

,,mean,sd,cv_1_valid,cv_2_valid,cv_3_valid,cv_4_valid,cv_5_valid
0,accuracy,0.837712,0.011739,0.838838,0.828147,0.853712,0.824607,0.843255
1,auc,0.893393,0.006174,0.899234,0.898108,0.895793,0.888702,0.885126
2,err,0.162288,0.011739,0.161162,0.171853,0.146288,0.175393,0.156745
3,err_count,811.200000,54.641560,810.000000,856.000000,737.000000,871.000000,782.000000
4,f0point5,0.661647,0.029072,0.660687,0.645140,0.700217,0.624666,0.677522
5,f1,0.693186,0.009161,0.704380,0.698804,0.694824,0.682233,0.685691
6,f2,0.730305,0.035418,0.754260,0.762204,0.689514,0.751487,0.694060
7,lift_top_group,3.981419,0.052133,3.937448,3.984664,3.965050,4.069252,3.950681
8,logloss,0.605426,0.061717,0.571482,0.539710,0.576008,0.653091,0.686838
9,max_per_class_error,0.241057,0.060922,0.208368,0.188725,0.313982,0.193966,0.300246
10,mcc,0.590686,0.010620,0.602336,0.592875,0.598729,0.577939,0.581550
11,mean_per_class_accuracy,0.810970,0.014056,0.822793,0.822459,0.796744,0.818151,0.794705
12,mean_per_class_error,0.189030,0.014056,0.177207,0.177541,0.203256,0.181849,0.205295
13,mse,0.101931,0.001457,0.100080,0.100905,0.102001,0.103148,0.103519
14,pr_auc,0.770476,0.013334,0.776812,0.785349,0.771482,0.749317,0.769420
15,precision,0.643122,0.045135,0.634451,0.613721,0.703859,0.591398,0.672183
16,r2,0.443824,0.013137,0.455242,0.455591,0.445120,0.423832,0.439335
17,recall,0.758943,0.060922,0.791632,0.811275,0.686018,0.806034,0.699754
18,rmse,0.319259,0.002283,0.316354,0.317656,0.319376,0.321167,0.321744
19,specificity,0.862998,0.034290,0.853953,0.833644,0.907470,0.830268,0.889655

Scoring History:

,,timestamp,duration,number_of_trees,training_rmse,training_logloss,training_auc,training_pr_auc,training_lift,training_classification_error
0,,2022-10-13 23:02:52,Û³.Û²Û³Û· sec,0.0,NaN,NaN,NaN,NaN,NaN,NaN

Variable Importances:

          variable  relative_importance  scaled_importance  percentage
0     relationship          2660.609619           1.000000    0.485785
1     capital.gain           825.940186           0.310433    0.150803
2       occupation           624.934387           0.234884    0.114103
3    education.num           488.642212           0.183658    0.089218
4              age           278.483643           0.104669    0.050847
5   hours.per.week           172.105469           0.064686    0.031424
6     capital.loss           163.981934           0.061633    0.029940
7   native.country           122.065704           0.045879    0.022287
8        workclass            62.606350           0.023531    0.011431
9   marital.status            41.184170           0.015479    0.007520
10          fnlwgt            13.458708           0.005059    0.002457
11            race            11.572126           0.004349    0.002113
12             sex            11.346861           0.004265    0.002072

<h3 align=right style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazir" color="#0099cc">
معیار ارزیابی
</font>
</h3>

<p dir=rtl style="direction: rtl; text-align: justify; line-height:200%; font-family:vazir; font-size:medium">
<font face="vazir" size=3>
    معیاری که برای ارزیابی عملکرد مدل انتخاب کرده‌ایم، <code>F1-score</code> نام دارد و کلاس مثبت (<code>pos_label</code>) را معادل <code dir=ltr>>50K</code> فرض کرده‌ایم، به این معنی که مدل شما باید برای پیش‌بینی درست افراد پردرآمد عملکرد مناسبی داشته باشد.
    <br>
    پیشنهاد می‌شود با توجه به این معیار، عملکرد مدل خود را بر روی مجموعه‌ی آموزش یا اعتبارسنجی ارزیابی کنید و طبق نتایج به‌دست‌آمده پارامترهای مدل خود را بهتر تنظیم کنید.
</font>
</p>

In [29]:
from sklearn.metrics import f1_score

sklearn_train_pr = clf.predict(sk_train)
sklearn_train_pr = [to_class[p] for p in sklearn_train_pr]
sklearn_test_pr = clf.predict(sk_test)
sklearn_test_pr = [to_class[p] for p in sklearn_test_pr]

h2o_train_pr = model.predict(hf_train)
h2o_test_pr = model.predict(hf_test)

print('Scikit-learn performance on training data:',
      f1_score(sklearn_train_pr, train_data['income'], pos_label='>50K'))

print('H2O performance on training data:',
      f1_score(h2o_train_pr.as_data_frame()['predict'], train_data['income'], pos_label='>50K'))

drf prediction progress: |███████████████████████████████████████████████████████| (done) 100%
drf prediction progress: |███████████████████████████████████████████████████████| (done) 100%

C:\Users\parsa\AppData\Roaming\Python\Python39\site-packages\h2o\job.py:83: UserWarning: Test/Validation dataset column 'native.country' has levels not trained on: ["Holand-Netherlands"]
  warnings.warn(w)

Scikit-learn performance on training data: 0.7134872417982988
H2O performance on training data: 0.704730533443133

<p dir=rtl style="direction: rtl; text-align: justify; line-height:200%; font-family:vazir; font-size:medium">
<font color="red"><b color='red'>توجه:</b></font>
<font face="vazir" size=3>
 جهت کسب امتیاز کامل نیاز است تا پاسخ شما حداقل امتیاز <code>66</code> را با توجه به معیار معرفی‌شده کسب نماید.
</font>
</p>

<h2 align=right style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazir" color="#0099cc">
 پیش‌بینی برای داده تست و خروجی
</font>
</h2>

<p dir=rtl style="direction: rtl; text-align: justify; line-height:200%; font-family:vazir; font-size:medium">
<font face="vazir" size=3>
    پس از مهندسی ویژگی و مدل‌سازی، الگوریتمی دارید که می‌تواند شما را از متغیرهای وابسته به متغیر هدف برساند.
    <br>
    از این مدل برای پیش‌بینی نمونه‌های موجود در مجموعه‌ی آزمون استفاده کنید و نتایج را در یک دیتافریم تک‌ستونه با نام <code>submission</code> و در قالب زیر آماده کنید. توجه داشته باشید که ترتیب پیش‌بینی شما اهمیت دارد یعنی به عنوان مثال پیش‌بینی مدل برای نمونه‌ی آزمون <code>m</code>ام را باید در ردیف <code>m</code>ام این دیتافریم ذخیره کنید.
</font>
</p>

<center>
<div dir=rtl style="direction: rtl;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazir" size=3>
    
|ستون|توضیحات|
|:------:|:---:|
|income|پیش‌بینی مدل شما (مقدار <code dir=ltr>>50K</code> یا <code dir=ltr><=50K</code>)|
    
</font>
</div>
</center>

In [34]:
submission = pd.DataFrame({'income': h2o_test_pr.as_data_frame()['predict']})

In [35]:
submission

     income
0     <=50K
1     <=50K
2      >50K
3     <=50K
4     <=50K
...     ...
7159  <=50K
7160  <=50K
7161  <=50K
7162  <=50K
7163  <=50K

[7164 rows x 1 columns]

<h2 align=right style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazir" color="#0099cc">
<b>سلول جواب‌ساز</b>
</font>
</h2>

<p dir=rtl style="direction: rtl; text-align: justify; line-height:200%; font-family:vazir; font-size:medium">
<font face="vazir" size=3>
    برای ساخته‌شدن فایل <code>result.zip</code> سلول زیر را اجرا کنید. توجه داشته باشید که پیش از اجرای سلول زیر تغییرات اعمال شده در نت‌بوک را ذخیره کرده باشید (<code>ctrl+s</code>) تا در صورت نیاز به پشتیبانی امکان بررسی کد شما وجود داشته باشد.
</font>
</p>

In [36]:
import zipfile
import joblib

def compress(file_names):
    print("File Paths:")
    print(file_names)
    compression = zipfile.ZIP_DEFLATED
    with zipfile.ZipFile("result.zip", mode="w") as zf:
        for file_name in file_names:
            zf.write('./' + file_name, file_name, compress_type=compression)

submission.to_csv('submission.csv', index=False)
file_names = ['income.ipynb', 'submission.csv']
compress(file_names)

File Paths:
['income.ipynb', 'submission.csv']

<h4 align=right style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazir" color="#0099cc">
<b>راهنمایی</b>
</font>
</h4>

<p dir=rtl style="direction: rtl; text-align: justify; line-height:200%; font-family:vazir; font-size:medium">
<font face="vazir" size=3>
    ۱. توازن مجموعه‌داده را بررسی و مدیریت کنید.
    <br>
    ۲. برای مقادیر گم‌شده چه در هنگام آموزش و چه هنگام آزمون چاره‌ای بی‌اندیشید.
    <br>
    ۳. مقادیر گم‌شده ممکن است با عبارت دیگری به جز مقدار <code>NaN</code> نشان داده شده باشد.
    <br>
    ۴. ویژگی‌های دسته‌ای را به‌خوبی مدیریت کنید. توجه داشته باشید که ممکن است در هنگام آزمون با دسته‌ای مواجه شوید که در نمونه‌های آموزشی رخ نداده باشد.
    <br>
    ۵. برای تعیین حداکثر عمق درخت می‌توانید یکبار درخت را به شکل آزاد و کامل بسازید، سپس عمق آن را مشاهده کنید. سپس می‌توانید مقادیر کمتر از آن را برای حداکثر عمق آزمایش و تحلیل کنید.
    <br>
    ۶. برای ارزیابی مدل خود و کشف مدل بهتر می‌توانید بخشی از مجموعه‌داده را به عنوان مجموعه‌ی اعتبارسنجی جدا کنید یا اینکه از تکنیک‌های اعتبارسنجی متقاطع (cross-validation) و مانند آن کمک بگیرید.
</font>
</p>